// <auto-generated />
using GreenGardenCatalog.Migrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GreenGardenCatalog.Migrations
{
    [DbContext(typeof(GreenGardenCatalogDbContext))]
    [Migration("20251110154746_Test")]
    partial class Test
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GreenGardenCatalog.Entities.Fertilizer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Fertilizers");
                });

            modelBuilder.Entity("GreenGardenCatalog.Entities.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FertilizedId")
                        .HasColumnType("int");

                    b.Property<int>("FertilizerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlantingSeason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoilId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FertilizerId");

                    b.HasIndex("SoilId");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("GreenGardenCatalog.Entities.Soil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Ph")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Soils");
                });

            modelBuilder.Entity("GreenGardenCatalog.Entities.Plant", b =>
                {
                    b.HasOne("GreenGardenCatalog.Entities.Fertilizer", "Fertilizer")
                        .WithMany("Plants")
                        .HasForeignKey("FertilizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenGardenCatalog.Entities.Soil", "Soil")
                        .WithMany("Plants")
                        .HasForeignKey("SoilId");

                    b.Navigation("Fertilizer");

                    b.Navigation("Soil");
                });

            modelBuilder.Entity("GreenGardenCatalog.Entities.Fertilizer", b =>
                {
                    b.Navigation("Plants");
                });

            modelBuilder.Entity("GreenGardenCatalog.Entities.Soil", b =>
                {
                    b.Navigation("Plants");
                });
#pragma warning restore 612, 618
        }
    }
}
